[package]
name = "jeremy-bearimy"
version = "0.1.0"
edition = "2024"

[features]
dev_tools = ["bevy_egui", "egui_plot"]

[dependencies]
bevy = "0.16.1"
bevy_enhanced_input = "0.14.1"
bevy_egui = { version = "0.35.1", optional = true }
egui_plot = {  version = "0.33.0", optional = true }
